version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - symfony

  postgres:
    image: postgres:latest
    container_name: 'postgresql'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'slaveapp_db'
      POSTGRES_USER: 'slave_user'
      POSTGRES_PASSWORD: '124fFv2GddQds'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - symfony

  php-fpm:
    container_name: 'php-fpm'
    build:
      context: ./php-fpm
    volumes:
      - ./../:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    environment:
      - .env
    depends_on:
      - postgres
    networks:
      - symfony

  admin:
      image: adminer
      restart: always
      depends_on: 
        - postgres
      ports:
        - 8080:8080
      networks:
      - symfony

networks:
  symfony :
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.221.0/28