version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: 'postgresql'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'db_name'
      POSTGRES_USER: 'db_user'
      POSTGRES_PASSWORD: 'db_pass'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - symfony

  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - postgres
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - /../:/var/www/html
    networks:
      - symfony

  nginx:
    image: nginx:latest
    container_name: 'nginx'
    ports:
      - '80:80'
    volumes:
      - ../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony